apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps-container
          image: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 21000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: lb-ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - port: 20
      name: ftp-data
      targetPort: 20
    - port: 21
      name: ftp-command
      targetPort: 21
    - port: 21000
      name: ftp-psv
      targetPort: 21000